### ISSUE TITLE
a question about formulation 4 in the paper

### ISSUE THREAD

**Issue by zhjscut** [NanqingD/DAOSL#1]
Hello! I would like to ask something about the formulation below:
![image](https://user-images.githubusercontent.com/32974196/54097591-dddaf280-43eb-11e9-80c9-b0524fb9cfff.png)
In my opinion, the highlighted part should be p(y=0|...), without the "1-". And your code in ada.py seems also prove it:
![image](https://user-images.githubusercontent.com/32974196/54097710-4d50e200-43ec-11e9-815d-ba1f57114c55.png)
So I feel a bit confused and want to turn to you for help. Is my thought wrong?

**Comment by eveningdong** [comment]
Hi, thank you very much.

It is a typo. You are right and follows my code.
